name: DockerHub
on:
  workflow_dispatch:
  push:
    branches: 
      - v3

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Clone Repository
      uses: actions/checkout@main

    - name: Build & Publish Image
      uses: ilteoood/docker_buildx@master
      with:
        publish: true
        imageName: ohmypatrick/jd-base
        tag: v3
        dockerFile: docker/Dockerfile
        platform: linux/amd64,linux/arm64,linux/arm/v7
        dockerUser: ${{ secrets.MY_ID }}
        dockerPassword: ${{ secrets.MY_PASSWORD }}
